services:
  ssui:
    container_name: ssui
    image: steamserverui/steamserverui:latest
    deploy:
      resources:
        limits:
          cpus: '8'
          memory: 16G
        reservations:
          cpus: '4'
          memory: 8G
    ports:
      - "8443:8443"
      - "27016:27016/udp"
      - "27016:27016/tcp"
      - "27015:27015/udp"
      - "27015:27015/tcp"
    volumes:
      - ./saves:/app/saves
      - ./UIMod/config:/app/UIMod/config:rw
    restart: unless-stopped
    user: "1000:1000"
    command: []