package api

// TemplateData holds data to be passed to templates
type IndexTemplateData struct {
	Version                        string
	Branch                         string
	SSUIIdentifier                 string
	UIText_StartButton             string
	UIText_StopButton              string
	UIText_Settings                string
	UIText_Update_SteamCMD         string
	UIText_Console                 string
	UIText_Detection_Events        string
	UIText_Backend_Log             string
	UIText_Backup_Manager          string
	UIText_Connected_PlayersHeader string
	UIText_Discord_Info            string
	UIText_API_Info                string
	UIText_Copyright1              string
	UIText_Copyright2              string
}

// ConfigTemplateData holds data for the config page template
type ConfigTemplateData struct {
	// Config values
	DiscordToken                            string
	ControlChannelID                        string
	StatusChannelID                         string
	ConnectionListChannelID                 string
	LogChannelID                            string
	SaveChannelID                           string
	ControlPanelChannelID                   string
	BlackListFilePath                       string
	ErrorChannelID                          string
	IsDiscordEnabled                        string
	IsDiscordEnabledTrueSelected            string
	IsDiscordEnabledFalseSelected           string
	GameBranch                              string
	Difficulty                              string
	StartCondition                          string
	StartLocation                           string
	ServerName                              string
	SaveName                                string
	WorldID                                 string
	ServerMaxPlayers                        string
	ServerPassword                          string
	ServerAuthSecret                        string
	AdminPassword                           string
	GamePort                                string
	UpdatePort                              string
	UPNPEnabled                             string
	UPNPEnabledTrueSelected                 string
	UPNPEnabledFalseSelected                string
	AutoSave                                string
	AutoSaveTrueSelected                    string
	AutoSaveFalseSelected                   string
	SaveInterval                            string
	AutoPauseServer                         string
	AutoPauseServerTrueSelected             string
	AutoPauseServerFalseSelected            string
	LocalIpAddress                          string
	StartLocalHost                          string
	StartLocalHostTrueSelected              string
	StartLocalHostFalseSelected             string
	ServerVisible                           string
	ServerVisibleTrueSelected               string
	ServerVisibleFalseSelected              string
	UseSteamP2P                             string
	UseSteamP2PTrueSelected                 string
	UseSteamP2PFalseSelected                string
	ExePath                                 string
	AdditionalParams                        string
	AutoRestartServerTimer                  string
	IsNewTerrainAndSaveSystem               string
	IsNewTerrainAndSaveSystemTrueSelected   string
	IsNewTerrainAndSaveSystemFalseSelected  string
	AutoStartServerOnStartup                string
	AutoStartServerOnStartupTrueSelected    string
	AutoStartServerOnStartupFalseSelected   string
	AllowAutoGameServerUpdates              string
	AllowAutoGameServerUpdatesTrueSelected  string
	AllowAutoGameServerUpdatesFalseSelected string

	UIText_ServerConfig         string
	UIText_DiscordIntegration   string
	UIText_DetectionManager     string
	UIText_ConfigurationWizard  string
	UIText_PleaseSelectSection  string
	UIText_UseWizardAlternative string
	UIText_BasicSettings        string
	UIText_NetworkSettings      string
	UIText_AdvancedSettings     string
	UIText_TerrainSettings      string
	UIText_BasicServerSettings  string

	UIText_ServerName                     string
	UIText_ServerNameInfo                 string
	UIText_SaveName                       string
	UIText_SaveNameInfo                   string
	UIText_WorldID                        string
	UIText_WorldIDInfo                    string
	UIText_MaxPlayers                     string
	UIText_MaxPlayersInfo                 string
	UIText_ServerPassword                 string
	UIText_ServerPasswordInfo             string
	UIText_AdminPassword                  string
	UIText_AdminPasswordInfo              string
	UIText_AutoSave                       string
	UIText_AutoSaveInfo                   string
	UIText_SaveInterval                   string
	UIText_SaveIntervalInfo               string
	UIText_AutoPauseServer                string
	UIText_AutoPauseServerInfo            string
	UIText_NetworkConfiguration           string
	UIText_GamePort                       string
	UIText_GamePortInfo                   string
	UIText_UpdatePort                     string
	UIText_UpdatePortInfo                 string
	UIText_UPNPEnabled                    string
	UIText_UPNPEnabledInfo                string
	UIText_LocalIpAddress                 string
	UIText_LocalIpAddressInfo             string
	UIText_StartLocalHost                 string
	UIText_StartLocalHostInfo             string
	UIText_ServerVisible                  string
	UIText_ServerVisibleInfo              string
	UIText_UseSteamP2P                    string
	UIText_UseSteamP2PInfo                string
	UIText_AdvancedConfiguration          string
	UIText_ServerAuthSecret               string
	UIText_ServerAuthSecretInfo           string
	UIText_ServerExePath                  string
	UIText_ServerExePathInfo              string
	UIText_ServerExePathInfo2             string
	UIText_AdditionalParams               string
	UIText_AdditionalParamsInfo           string
	UIText_AutoRestartServerTimer         string
	UIText_AutoRestartServerTimerInfo     string
	UIText_GameBranch                     string
	UIText_GameBranchInfo                 string
	UIText_TerrainSettingsHeader          string
	UIText_TerrainWarning                 string
	UIText_UseNewTerrainAndSave           string
	UIText_UseNewTerrainAndSaveInfo       string
	UIText_Difficulty                     string
	UIText_DifficultyInfo                 string
	UIText_StartCondition                 string
	UIText_StartConditionInfo             string
	UIText_StartLocation                  string
	UIText_StartLocationInfo              string
	UIText_TerrainSettingsFillHint        string
	UIText_AutoStartServerOnStartup       string
	UIText_AutoStartServerOnStartupInfo   string
	UIText_AllowAutoGameServerUpdates     string
	UIText_AllowAutoGameServerUpdatesInfo string

	UIText_DiscordIntegrationTitle    string
	UIText_DiscordBotToken            string
	UIText_DiscordBotTokenInfo        string
	UIText_ChannelConfiguration       string
	UIText_AdminCommandChannel        string
	UIText_AdminCommandChannelInfo    string
	UIText_ControlPanelChannel        string
	UIText_ControlPanelChannelInfo    string
	UIText_StatusChannel              string
	UIText_StatusChannelInfo          string
	UIText_ConnectionListChannel      string
	UIText_ConnectionListChannelInfo  string
	UIText_LogChannel                 string
	UIText_LogChannelInfo             string
	UIText_SaveInfoChannel            string
	UIText_SaveInfoChannelInfo        string
	UIText_ErrorChannel               string
	UIText_ErrorChannelInfo           string
	UIText_BannedPlayersListPath      string
	UIText_BannedPlayersListPathInfo  string
	UIText_DiscordIntegrationBenefits string
	UIText_DiscordBenefit1            string
	UIText_DiscordBenefit2            string
	UIText_DiscordBenefit3            string
	UIText_DiscordBenefit4            string
	UIText_DiscordBenefit5            string
	UIText_DiscordSetupInstructions   string

	UIText_Copyright        string
	UIText_CopyrightConfig1 string
	UIText_CopyrightConfig2 string
}
